/**
 * Schema Builder
 * Builds D1/SQLite compatible schemas from source schemas
 */

import { Logger } from '@zintrust/core';
import type { ColumnSchema, TableSchema } from '../types';
import { DataValidator } from '../utils/DataValidator';
import { TypeConverter } from './TypeConverter';

/**
 * SchemaBuilder - Sealed namespace for schema building
 * Provides D1 schema generation from source schemas
 */
export const SchemaBuilder = Object.freeze({
  /**
   * Build D1 schema from source schema
   */
  buildD1Schema(sourceSchema: TableSchema[], sourceDriver: string): TableSchema[] {
    Logger.info('Building D1 schema...');

    return sourceSchema.map((table) => SchemaBuilder.buildD1Table(table, sourceDriver));
  },

  /**
   * Build D1 table from source table
   */
  buildD1Table(sourceTable: TableSchema, sourceDriver: string): TableSchema {
    const sanitizedTableName = DataValidator.sanitizeTableName(sourceTable.name);

    const d1Table: TableSchema = {
      name: sanitizedTableName,
      columns: sourceTable.columns.map((column) =>
        SchemaBuilder.buildD1Column(column, sourceDriver)
      ),
      primaryKey: sourceTable.primaryKeys?.[0] || '',
      indexes: sourceTable.indexes || [],
    };

    Logger.info(`Converted table: ${sourceTable.name} -> ${sanitizedTableName}`);
    return d1Table;
  },

  /**
   * Build D1 column from source column
   */
  buildD1Column(sourceColumn: ColumnSchema, sourceDriver: string): ColumnSchema {
    const d1Type = TypeConverter.convertToD1Type(sourceColumn.type, sourceDriver);
    const warnings = TypeConverter.getConversionWarnings(sourceColumn.type, d1Type);

    // Log conversion warnings
    warnings.forEach((warning) => {
      Logger.warn(`Column conversion warning: ${sourceColumn.name} - ${warning}`);
    });

    const d1Column: ColumnSchema = {
      name: sourceColumn.name,
      type: d1Type,
      nullable: sourceColumn.nullable,
      defaultValue: sourceColumn.defaultValue,
    };

    return d1Column;
  },

  /**
   * Generate CREATE TABLE SQL
   */
  generateCreateTableSQL(table: TableSchema): string {
    let sql = `CREATE TABLE \`${table.name}\` (\n`;

    const columnDefinitions = table.columns.map((column) =>
      SchemaBuilder.generateColumnDefinition(column)
    );

    sql += columnDefinitions.join(',\n');

    if (table.primaryKey) {
      const keyList = table.primaryKey;
      sql += `,\n  PRIMARY KEY (${keyList})`;
    }

    sql += '\n);';

    return sql;
  },

  /**
   * Generate column definition
   */
  generateColumnDefinition(column: ColumnSchema): string {
    let definition = `  \`${column.name}\` ${column.type}`;

    if (!column.nullable) {
      definition += ' NOT NULL';
    }

    if (column.defaultValue !== undefined) {
      definition += ` DEFAULT ${SchemaBuilder.formatDefaultValue(column.defaultValue)}`;
    }

    return definition;
  },

  /**
   * Format default value for SQL
   */
  formatDefaultValue(value: unknown): string {
    if (value === null) {
      return 'NULL';
    }

    if (typeof value === 'string') {
      return `'${value.replaceAll("'", "''")}'`;
    }

    if (typeof value === 'boolean') {
      return value ? '1' : '0';
    }

    return String(value);
  },

  /**
   * Generate index statements
   */
  generateIndexSQL(table: TableSchema): string[] {
    const indexes: string[] = [];

    if (table.indexes) {
      table.indexes.forEach((index) => {
        const indexName = `idx_${table.name}_${index.columns.join('_')}`;
        const columns = index.columns.map((col) => `\`${col}\``).join(', ');

        let sql = `CREATE`;
        if (index.unique) {
          sql += ' UNIQUE';
        }
        sql += ` INDEX \`${indexName}\` ON \`${table.name}\` (${columns});`;

        indexes.push(sql);
      });
    }

    return indexes;
  },

  /**
   * Generate complete schema SQL
   */
  generateSchemaSQL(tables: TableSchema[]): string {
    let sql = '-- D1 Schema Migration\n';
    sql += '-- Generated by ZinTrust D1 Migrator\n\n';

    tables.forEach((table) => {
      sql += SchemaBuilder.generateCreateTableSQL(table);
      sql += '\n\n';

      const indexes = SchemaBuilder.generateIndexSQL(table);
      indexes.forEach((indexSql) => {
        sql += indexSql + '\n';
      });

      if (indexes.length > 0) {
        sql += '\n';
      }
    });

    return sql;
  },

  /**
   * Validate built schema
   */
  validateSchema(tables: TableSchema[]): {
    valid: boolean;
    errors: string[];
  } {
    const errors: string[] = [];

    tables.forEach((table) => {
      // Check table name
      if (!DataValidator.sanitizeTableName(table.name)) {
        errors.push(`Invalid table name: ${table.name}`);
      }

      // Check columns
      table.columns.forEach((column) => {
        if (!column.name || column.name.trim() === '') {
          errors.push(`Empty column name in table: ${table.name}`);
        }

        if (!column.type || column.type.trim() === '') {
          errors.push(`Empty column type: ${table.name}.${column.name}`);
        }
      });

      if (table.primaryKey) {
        const hasPrimaryKeyColumn = table.columns.some(
          (column) => column.name === table.primaryKey
        );
        if (!hasPrimaryKeyColumn) {
          errors.push(`Primary key column '${table.primaryKey}' not found in table: ${table.name}`);
        }
      }
    });

    return {
      valid: errors.length === 0,
      errors,
    };
  },
});
