/**
 * GenerateEnvArtifacts
 * - Generates env.d.ts and .env.example from the framework's Env usage.
 *
 * Goals:
 * - Developer convenience (discoverable env keys)
 * - Keep env.d.ts + .env.example in sync with src/config usage
 *
 * Usage:
 *   tsx src/scripts/GenerateEnvArtifacts.ts
 */

import { Logger } from '@config/logger';
import { ErrorFactory } from '@exceptions/ZintrustError';
import fs from '@node-singletons/fs';
import * as path from '@node-singletons/path';

type EnvUsage = {
  key: string;
  defaultValue?: string;
};

const ROOT_DIR = path.resolve(process.cwd());

const walkDir = (dirAbs: string): string[] => {
  const out: string[] = [];
  const entries = fs.readdirSync(dirAbs, { withFileTypes: true });
  for (const entry of entries) {
    if (entry.name === 'node_modules' || entry.name === 'dist' || entry.name === 'coverage')
      continue;
    const abs = path.join(dirAbs, entry.name);
    if (entry.isDirectory()) {
      out.push(...walkDir(abs));
      continue;
    }
    if (entry.isFile() && entry.name.endsWith('.ts')) out.push(abs);
  }
  return out;
};

const readText = (fileAbs: string): string => fs.readFileSync(fileAbs, 'utf8');

const uniq = <T>(arr: T[]): T[] => Array.from(new Set(arr));

const parseEnvUsages = (content: string): EnvUsage[] => {
  const out: EnvUsage[] = [];

  // Env.get('KEY', 'default')
  const rxGet = /Env\.get\(\s*['"]([A-Z0-9_]+)['"]\s*(?:,\s*([^)]+?))?\)/g;
  // Env.getInt('KEY', 123)
  const rxGetInt = /Env\.getInt\(\s*['"]([A-Z0-9_]+)['"]\s*(?:,\s*([^)]+?))?\)/g;
  // Env.getBool('KEY', true)
  const rxGetBool = /Env\.getBool\(\s*['"]([A-Z0-9_]+)['"]\s*(?:,\s*([^)]+?))?\)/g;

  const collect = (rx: RegExp): void => {
    let m: RegExpExecArray | null;
    while ((m = rx.exec(content)) !== null) {
      const key = m[1];
      const rawDefault = m[2]?.trim();
      out.push({ key, defaultValue: rawDefault });
    }
  };

  collect(rxGet);
  collect(rxGetInt);
  collect(rxGetBool);

  return out;
};

const renderEnvDts = (keys: string[]): string => {
  const sortedKeys = keys.toSorted((a, b) => a.localeCompare(b));
  const lines = sortedKeys.map((k) => `    ${k}?: string | undefined;`).join('\n');

  return `declare namespace NodeJS {\n  interface ProcessEnv {\n    NODE_ENV: 'development' | 'production' | 'testing' | undefined;\n\n${lines}\n  }\n}\n`;
};

const renderEnvExample = (keys: string[]): string => {
  const header = `# Zintrust Framework - Environment Configuration\n# Generated by src/scripts/GenerateEnvArtifacts.ts\n# Copy this file to .env and configure for your environment\n\n`;
  const sortedKeys = keys.toSorted((a, b) => a.localeCompare(b));
  const body = sortedKeys
    .filter((k) => k !== 'NODE_ENV')
    .map((k) => `${k}=`)
    .join('\n');
  return header + `NODE_ENV=development\n` + body + `\n`;
};

const writeIfChanged = (fileAbs: string, next: string): void => {
  const prev = fs.existsSync(fileAbs) ? fs.readFileSync(fileAbs, 'utf8') : '';
  if (prev === next) return;
  fs.writeFileSync(fileAbs, next, 'utf8');
};

const main = (): void => {
  try {
    const configDir = path.join(ROOT_DIR, 'src', 'config');
    const configFiles = walkDir(configDir);

    const usages = configFiles.flatMap((f) => parseEnvUsages(readText(f)));
    const keys = uniq(usages.map((u) => u.key));

    if (keys.length === 0) {
      throw ErrorFactory.createTryCatchError('No Env.get usages found under src/config');
    }

    // env.d.ts
    const envDtsPath = path.join(ROOT_DIR, 'env.d.ts');
    writeIfChanged(envDtsPath, renderEnvDts(keys));

    // .env.example
    const envExamplePath = path.join(ROOT_DIR, '.env.example');
    writeIfChanged(envExamplePath, renderEnvExample(keys));

    Logger.info(`✓ Generated env artifacts (keys: ${keys.length})`);
  } catch (error) {
    Logger.error('GenerateEnvArtifacts failed', error);
    process.exit(1);
  }
};

main();
